---
- hosts: web
  tasks:
  - package:
        name: "httpd"
        state: present
        use: yum
  - copy:
        src: "/local/web.conf"
        dest: "/etc/httpd/conf.d"
  - file:
        path: "/web_serve"
        state: directory
  - copy:
        src: "/local/index.html"
        dest: "/web_serve"
  - service:
        name: "httpd"
        state: "restarted"

